// ==========================================================================
// BulkCerts Certificate PDF and ZIP Generation Engine
// ==========================================================================

// Helper to sanitize filenames for ZIP packaging
function sanitizeFilename(row, index) {
    let name = row.name ? String(row.name).trim() : '';
    let course = row.course ? String(row.course).trim() : '';
    
    let baseName = '';
    if (name && course) {
        baseName = `${name}_${course}`;
    } else if (name) {
        baseName = name;
    } else if (course) {
        baseName = course;
    } else {
        baseName = `Certificate_${index + 1}`;
    }
    
    // Replace invalid file system characters: / \ ? % * : | " < >
    return baseName.replace(/[\/\\?%*:|"<>]/g, '_').substring(0, 100);
}

// Helper to substitute placeholders in text fields
function substitutePlaceholders(text, row) {
    if (!text) return '';
    let result = text;
    
    // Replace placeholders matching {column_name} (case insensitive)
    for (const key in row) {
        if (Object.prototype.hasOwnProperty.call(row, key)) {
            const placeholder = `{${key}}`;
            const value = row[key] !== undefined ? String(row[key]) : '';
            // Regex escape helper
            const escapedPlaceholder = placeholder.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
            result = result.replace(new RegExp(escapedPlaceholder, 'gi'), value);
        }
    }
    return result;
}

// Core rendering function that draws page background & overlays
function renderCertificatePage(drawCtx, row, state, addWatermark) {
    // 1. Draw Template Background
    const activeTemplate = window.BulkCertsTemplates[state.background];
    if (activeTemplate) {
        // PDF export needs the base64 data URL; canvas preview uses the Image element
        activeTemplate.drawBackground(drawCtx, state.backgroundImageSrc || state.backgroundImage);
    }
    
    // 2. Draw Elements (Text Variables & Uploaded Images)
    state.elements.forEach(elem => {
        if (elem.type === 'text') {
            const renderedText = substitutePlaceholders(elem.text, row);
            drawCtx.text(
                renderedText,
                elem.x,
                elem.y,
                elem.font || 'helvetica',
                elem.fontStyle || 'normal',
                elem.fontSize || 12,
                elem.color || '#000000',
                elem.align || 'left'
            );
        } else if (elem.type === 'image') {
            // elem.src is the base64 data URL
            drawCtx.image(elem.src, elem.x, elem.y, elem.width, elem.height);
        }
    });
    
    // 3. Draw Watermark if enabled
    if (addWatermark) {
        drawCtx.text(
            'Generated by BulkCerts',
            290,
            205,
            'helvetica',
            'normal',
            7,
            '#94a3b8',
            'right'
        );
    }
}

/**
 * Main function to generate bulk certificates asynchronously
 * @param {Object} state - The builder state (background, backgroundImage, elements, excelData)
 * @param {Object} options - Export options (format: 'zip'|'pdf', watermark: boolean)
 * @param {Function} onProgress - Progress callback ({ processed, total, phase })
 * @param {Function} onComplete - Success callback (blob, filename)
 * @param {Function} onError - Error callback (errorMsg)
 */
async function generateBulkCertificates(state, options, onProgress, onComplete, onError) {
    try {
        const data = state.excelData;
        if (!data || data.length === 0) {
            throw new Error("No recipient data available for generation.");
        }
        
        const total = data.length;
        const format = options.format || 'zip';
        const addWatermark = !!options.watermark;
        
        const { jsPDF } = window.jspdf;
        
        if (format === 'zip') {
            const zip = new JSZip();
            
            // Loop and process in yields to keep UI snappy
            for (let i = 0; i < total; i++) {
                onProgress({ processed: i, total, phase: 'generating' });
                
                // Create single A4 landscape PDF
                const doc = new jsPDF({
                    orientation: 'landscape',
                    unit: 'mm',
                    format: 'a4',
                    compress: true
                });
                
                const pdfCtx = new window.PDFDrawingContext(doc);
                renderCertificatePage(pdfCtx, data[i], state, addWatermark);
                
                // Output arraybuffer and save to ZIP
                const pdfBytes = doc.output('arraybuffer');
                const filename = `${sanitizeFilename(data[i], i)}.pdf`;
                zip.file(filename, pdfBytes);
                
                // Yield control back to browser main thread
                await new Promise(resolve => setTimeout(resolve, 0));
            }
            
            // Package ZIP
            onProgress({ processed: total, total, phase: 'packaging' });
            const zipBlob = await zip.generateAsync({
                type: 'blob',
                compression: 'DEFLATE',
                compressionOptions: { level: 5 }
            });
            
            onComplete(zipBlob, 'BulkCerts_Export.zip');
            
        } else if (format === 'pdf') {
            // Create a single multi-page PDF
            const doc = new jsPDF({
                orientation: 'landscape',
                unit: 'mm',
                format: 'a4',
                compress: true
            });
            
            const pdfCtx = new window.PDFDrawingContext(doc);
            
            for (let i = 0; i < total; i++) {
                onProgress({ processed: i, total, phase: 'generating' });
                
                if (i > 0) {
                    doc.addPage();
                }
                
                renderCertificatePage(pdfCtx, data[i], state, addWatermark);
                
                // Yield control back to browser main thread
                await new Promise(resolve => setTimeout(resolve, 0));
            }
            
            onProgress({ processed: total, total, phase: 'packaging' });
            const pdfBlob = doc.output('blob');
            onComplete(pdfBlob, 'BulkCerts_Export.pdf');
        } else {
            throw new Error(`Unsupported export format: ${format}`);
        }
        
    } catch (err) {
        console.error("Bulk certificate generation failed:", err);
        onError(err.message || "An unexpected error occurred during PDF generation.");
    }
}

// Global export for generator
window.generateBulkCertificates = generateBulkCertificates;
window.renderCertificatePage = renderCertificatePage;
window.substitutePlaceholders = substitutePlaceholders;
